# Generated by Django 3.2.6 on 2021-08-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_3d',
            field=models.FileField(null=True, upload_to='', verbose_name='فایل سه بعدی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_3d_1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='فایل سه بعدی'),
        ),
    ]
