# Generated by Django 3.2.6 on 2021-08-30 09:52

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210830_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=products.models.upload_image_path, verbose_name='عکس محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path, verbose_name='ادیت محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_3d',
            field=models.FileField(null=True, upload_to=products.models.upload_image_path, verbose_name='فایل سه بعدی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_3d_1',
            field=models.FileField(blank=True, null=True, upload_to=products.models.upload_image_path, verbose_name='فایل سه بعدی'),
        ),
    ]
