# Generated by Django 3.2.6 on 2021-08-31 11:29

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210831_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='model_3d',
            new_name='model_3dm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_3d_1',
        ),
        migrations.AddField(
            model_name='product',
            name='model_3dm_1',
            field=models.FileField(blank=True, null=True, upload_to=products.models.upload_image_path, verbose_name='ادیت فایل سه بعدی'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_stl',
            field=models.FileField(null=True, upload_to=products.models.upload_image_path, verbose_name='فایل سه بعدی'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_stl_1',
            field=models.FileField(blank=True, null=True, upload_to=products.models.upload_image_path, verbose_name='ادیت فایل سه بعدی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بیشتر'),
        ),
    ]
