# Generated by Django 3.2.6 on 2021-08-31 11:36

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210831_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_3dm_1',
            field=models.FileField(blank=True, null=True, upload_to=products.models.upload_image_path, verbose_name='ادیت فایل سه بعدی (3DM)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_stl_1',
            field=models.FileField(blank=True, null=True, upload_to=products.models.upload_image_path, verbose_name='ادیت فایل سه بعدی (STL)'),
        ),
    ]
