# Generated by Django 3.2.6 on 2021-09-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category', verbose_name='عکس دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product', to='products.Category', verbose_name='دسته\u200cبندی'),
        ),
    ]
