# Generated by Django 3.2.6 on 2021-10-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210904_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='product',
            name='technique',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='تکنیک'),
        ),
    ]
