# Generated by Django 3.2.6 on 2021-10-14 07:33

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20211014_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path, verbose_name='عکس محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_3dm',
            field=models.FileField(blank=True, null=True, upload_to=products.models.upload_image_path, verbose_name='فایل سه بعدی (3DM)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_stl',
            field=models.FileField(blank=True, null=True, upload_to=products.models.upload_image_path, verbose_name='فایل سه بعدی (STL)'),
        ),
    ]
