# Generated by Django 3.2.6 on 2021-10-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20211014_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='آدرس دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'کالکشن',
                'verbose_name_plural': 'کالکشن ها',
            },
        ),
    ]
