# Generated by Django 3.2.6 on 2021-10-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='شناسه کالکشن'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان کالکشن'),
        ),
    ]
